const matches = {
    upper: [
        {
            id: 101,
            name: "UB 1.1",
            nextMatchId: 301,
            tournamentRoundText: "UB 1",
            startTime: "Match1",
            state: "SCORE_DONE",
            participants: [
                {
                    id: "8cf422cd-a99d-4184-b2cd-70ee481f46b3",
                    resultText: "2",
                    isWinner: true,
                    status: "PLAYED",
                    name: "TEAM - 01",
                },
                {
                    id: "e1e48aad-5e29-41dc-b904-16f152a7ec74",
                    resultText: "0",
                    isWinner: false,
                    status: "PLAYED",
                    name: "TEAM - 02",
                },
            ],
            index: 0,
            round: 0,
            isUpperBracket: true,
        },
        {
            id: 102,
            name: "UB 1.2",
            nextMatchId: 301,
            tournamentRoundText: "UB 1",
            startTime: "Match 2",
            state: "SCORE_DONE",
            participants: [
                {
                    id: "a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0",
                    resultText: "2",
                    isWinner: true,
                    status: "PLAYED",
                    name: "TEAM - 03",
                },
                {
                    id: "12046e66-adbf-49d9-98c1-bed16d5ced29",
                    resultText: "1",
                    isWinner: false,
                    status: "PLAYED",
                    name: "TEAM - 04",
                },
            ],
            index: 1,
            round: 0,
            isUpperBracket: true,
        },
        {
            id: 103,
            name: "UB 1.3",
            nextMatchId: 302,
            tournamentRoundText: "UB 1",
            startTime: "Match 4",
            state: "SCORE_DONE",
            participants: [
                {
                    id: "3d1a5ddb-85b7-4724-b94d-8747454d66e9",
                    resultText: "2",
                    isWinner: true,
                    status: "PLAYED",
                    name: "TEAM - 05",
                },
                {
                    id: "fabb2218-49d6-41a2-874c-d6cd6928df70",
                    resultText: "1",
                    isWinner: false,
                    status: "PLAYED",
                    name: "TEAM - 06",
                },
            ],
            index: 2,
            round: 0,
            isUpperBracket: true,
        },
        {
            id: 104,
            name: "Match 3",
            nextMatchId: 302,
            tournamentRoundText: "UB 1",
            startTime: "Match 3",
            state: "SCORE_DONE",
            participants: [
                {
                    id: "dd6c4bff-80da-449c-8bfa-24c835af013a",
                    resultText: "0",
                    isWinner: false,
                    status: "PLAYED",
                    name: "TEAM - 07",
                },
                {
                    id: "a3c107d2-ded2-4f33-85e7-2215805f664b",
                    resultText: "2",
                    isWinner: true,
                    status: "PLAYED",
                    name: "TEAM - 08",
                },
            ],
            index: 3,
            round: 0,
            isUpperBracket: true,
        },
        {
            id: 301,
            name: "UB 2.1",
            nextMatchId: 501,
            tournamentRoundText: "UB 2",
            startTime: "Match 9",
            state: "SCORE_DONE",
            participants: [
                {
                    id: "8cf422cd-a99d-4184-b2cd-70ee481f46b3",
                    resultText: "0",
                    isWinner: false,
                    status: "PLAYED",
                    name: "TEAM - 01",
                },
                {
                    id: "a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0",
                    resultText: "2",
                    isWinner: true,
                    status: "PLAYED",
                    name: "TEAM - 03",
                },
            ],
        },
        {
            id: 302,
            name: "UB 2.2",
            nextMatchId: 501,
            tournamentRoundText: "UB 2",
            startTime: "Match 10",
            state: "SCORE_DONE",
            participants: [
                {
                    id: "a3c107d2-ded2-4f33-85e7-2215805f664b",
                    resultText: "2",
                    isWinner: true,
                    status: "PLAYED",
                    name: "TEAM - 08",
                },
                {
                    id: "3d1a5ddb-85b7-4724-b94d-8747454d66e9",
                    resultText: "1",
                    isWinner: false,
                    status: "PLAYED",
                    name: "TEAM - 05",
                },
            ],
        },
        {
            id: 501,
            name: "UB 3.1",
            nextMatchId: 801,
            tournamentRoundText: "UB 3",
            startTime: "August 05, 2021",
            state: "SCORE_DONE",
            participants: [
                {
                    id: "a3c107d2-ded2-4f33-85e7-2215805f664b",
                    resultText: "0",
                    isWinner: false,
                    status: "PLAYED",
                    name: "TEAM - 08",
                },
                {
                    id: "a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0",
                    resultText: "2",
                    isWinner: true,
                    status: "PLAYED",
                    name: "TEAM - 03",
                },
            ],
        },
        {
            id: 801,
            name: "Final",
            nextMatchId: null,
            tournamentRoundText: "UB 4",
            startTime: "August 05, 2021",
            state: "SCORE_DONE",
            participants: [
                {
                    id: "3d1a5ddb-85b7-4724-b94d-8747454d66e9",
                    resultText: "2",
                    isWinner: true,
                    status: "PLAYED",
                    name: "TEAM - 05",
                },
                {
                    id: "a3fb4b05-d4ee-4efe-84cf-b500cdbdbbe0",
                    resultText: "1",
                    isWinner: false,
                    status: "PLAYED",
                    name: "TEAM - 03",
                },
            ],
        },
    ],
};

export default matches;
